from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
# from django.utils import timezone

from .forms import BlogPostModelForm
from .models import BlogPost


# get  --> returns 1 value
# filter  --> returns [] of values so we can apply index also on filter


def blog_post_list_view(request):
    # List out objects
    # could be search

    # now = timezone.now()
    # qs = BlogPost.objects.filter(publish_date__lte=now)
    qs = BlogPost.objects.all().published()

    template_name = 'blog/list.html'
    context = {"title": "Blog",
               "object_list": qs}
    return render(request, template_name, context)


# @login_required
@staff_member_required
def blog_post_create_view(request):
    # Create object
    # ? Use a form
    # request.user  --> Return something because of decorators
    form = BlogPostModelForm(request.POST or None)
    if form.is_valid():
        # create object with key: value pair of dict data generated by form.cleaned_data
        # obj = BlogPost.objects.create(**form.cleaned_data)
        obj = form.save(commit=False)
        obj.user = request.user
        obj.save()
        form = BlogPostModelForm()

    template_name = 'blog/post_form.html'
    context = {"title": "Create New Post",
               "form": form}
    return render(request, template_name, context)


def blog_post_detail_view(request, slug):
    # 1 object --> Detail view
    obj = get_object_or_404(BlogPost, slug=slug)

    template_name = "blog/detail.html"
    context = {"object": obj}
    return render(request, template_name, context)


@staff_member_required
def blog_post_update_view(request, slug):
    obj = get_object_or_404(BlogPost, slug=slug)
    form = BlogPostModelForm(request.POST or None, instance=obj)
    if form.is_valid():
        form.save()

    template_name = "blog/post_form.html"
    context = {"title": f"Update {obj.title}",
               "form": form}
    return render(request, template_name, context)


@staff_member_required
def blog_post_delete_view(request, slug):
    obj = get_object_or_404(BlogPost, slug=slug)
    if request.method == 'POST':
        obj.delete()
        return redirect('/blog')

    template_name = "blog/delete.html"
    context = {"object": obj}
    return render(request, template_name, context)
