from django.http import Http404
from django.shortcuts import render, get_object_or_404

from .forms import BlogPostForm
from .models import BlogPost


# get  --> returns 1 value
# filter  --> returns [] of values so we can apply index also on filter


def blog_post_list_view(request):
    # List out objects
    # could be search
    qs = BlogPost.objects.all()
    template_name = 'blog/list.html'
    context = {"object_list": qs}
    return render(request, template_name, context)


def blog_post_create_view(request):
    # Create object
    # ? Use a form
    form = BlogPostForm(request.POST or None)
    if form.is_valid():
        # create object with key: value pair of dict data generated by form.cleaned_data
        obj = BlogPost.objects.create(**form.cleaned_data)
        form = BlogPostForm()
    template_name = 'blog/form.html'
    context = {"title": "Create New Post",
               "form": form}
    return render(request, template_name, context)


def blog_post_detail_view(request, slug):
    # 1 object --> Detail view
    obj = get_object_or_404(BlogPost, slug=slug)
    template_name = "blog/detail.html"
    context = {"object": obj}
    return render(request, template_name, context)


def blog_post_update_view(request, slug):
    obj = get_object_or_404(BlogPost, slug=slug)
    template_name = "blog/update.html"
    context = {"object": obj, "form": None}
    return render(request, template_name, context)


def blog_post_delete_view(request, slug):
    obj = get_object_or_404(BlogPost, slug=slug)
    template_name = "blog/delete.html"
    context = {"object": obj}
    return render(request, template_name, context)
